// Generated by contracts/scripts/export-addresses.cjs after a Sepolia deployment.
import type { Address } from "viem";

export type FreelanceShieldContractConfig = {
  chainId: 11155111;
  network: "sepolia";
  escrowImplementation: Address | null;
  disputeResolver: Address | null;
  reputationRegistry: Address | null;
  escrowFactory: Address | null;
};

export const freelanceShieldContracts: FreelanceShieldContractConfig = {
  "chainId": 11155111,
  "network": "sepolia",
  "escrowImplementation": "0xDDb2824E9f968Bb89085c26d71703f22ef7db69C",
  "disputeResolver": "0x822578A8825f4b78BC2E9AA99F0E3672df17B7dA",
  "reputationRegistry": "0xabCd60022f4567520C3145b540999A9601655CfD",
  "escrowFactory": "0xaA3923a7deFaf0D925E22ECC3208d5f3B405A8f0"
};
